syntax = "proto2";

package common.v2;

message SsoSecureInfo {
  optional bytes sec_sign = 1;
  optional bytes sec_token = 2;
  optional bytes sec_extra = 3;
}

message SsoReserveFields {
  optional bytes client_ip_cookie = 8;
  optional uint32 flag = 9;
  optional uint32 env_id = 10;
  optional uint32 locale_id = 11;
  optional string qimei = 12;
  optional bytes env = 13;
  optional uint32 new_conn_flag = 14;
  optional string trace_parent = 15;
  optional string uid = 16;
  optional uint32 imsi = 18;
  optional uint32 network_type = 19;
  optional uint32 ip_stack_type = 20;
  optional uint32 msg_type = 21;
  optional string trpc_rsp = 22;
  map<string, string> trans_info = 23;
  optional SsoSecureInfo sec_info = 24;
  optional uint32 sec_sig_flag = 25;
  optional uint32 nt_core_version = 26;
  optional uint32 sso_route_cost = 27;
  optional uint32 sso_ip_origin = 28;
  optional bytes presure_token = 30;
}
